# Generated by Django 5.0.6 on 2024-05-20 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Men',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Мінімум 5 символів'), django.core.validators.MaxLengthValidator(100, message='Максимум 100 символів')], verbose_name='Slug')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('content', models.TextField(blank=True, verbose_name='Текст статті')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Час зміни')),
            ],
            options={
                'verbose_name': 'Математики',
                'verbose_name_plural': 'Математики',
                'ordering': ['-time_create'],
                'indexes': [models.Index(fields=['-time_create'], name='men_men_time_cr_642e6a_idx')],
            },
        ),
    ]
